const bancoPreguntas = {
    "ALG": [
        { q: "¿Cuál es el apodo de la selección de Argelia?", options: ["Los Leones", "Zorros del Desierto", "Las Águilas", "Los Faraones"], correct: 1 },
        { q: "¿En qué Mundial Argelia le ganó a Alemania Federal (2-1)?", options: ["España 82", "México 86", "Sudáfrica 2010", "Brasil 2014"], correct: 0 },
        { q: "¿A qué fase llegó Argelia en el Mundial de Brasil 2014?", options: ["Fase de grupos", "Octavos de final", "Cuartos", "Semifinales"], correct: 1 },
        { q: "¿Quién es el capitán y estrella que jugó en el Manchester City?", options: ["Islam Slimani", "Riyad Mahrez", "Sofiane Feghouli", "Yacine Brahimi"], correct: 1 },
        { q: "¿Cuál es el color principal de su uniforme de local?", options: ["Blanco", "Rojo", "Azul", "Amarillo"], correct: 0 },
        { q: "¿Contra qué selección perdió Argelia en los octavos de 2014?", options: ["Francia", "Alemania", "Argentina", "Bélgica"], correct: 1 },
        { q: "¿Quién es el máximo goleador histórico de Argelia?", options: ["Islam Slimani", "Riyad Mahrez", "Rabah Madjer", "Lakhdar Belloumi"], correct: 0 },
        { q: "¿Qué país eliminó a Argelia en el repechaje para 2022?", options: ["Egipto", "Camerún", "Senegal", "Marruecos"], correct: 1 },
        { q: "¿En qué confederación juega Argelia?", options: ["CAF", "AFC", "UEFA", "CONMEBOL"], correct: 0 },
        { q: "¿Qué argelino inventó el gol de 'taco' en una final europea?", options: ["Riyad Mahrez", "Rabah Madjer", "Djamel Belmadi", "Faouzi Ghoulam"], correct: 1 }
    ],
    "KSA": [
        { q: "¿A qué selección campeona del mundo derrotó Arabia en 2022?", options: ["Brasil", "Francia", "Argentina", "Alemania"], correct: 2 },
        { q: "¿Cuál es el apodo de la selección saudí?", options: ["Hijos del Desierto", "Águilas Blancas", "Halcones Verdes", "Tigres de Asia"], correct: 2 },
        { q: "¿En qué Mundial Arabia Saudita llegó a octavos por primera vez?", options: ["1990", "1994", "1998", "2002"], correct: 1 },
        { q: "¿Quién anotó un gol recorriendo medio campo contra Bélgica en 1994?", options: ["Saeed Al-Owairan", "Sami Al-Jaber", "Salem Al-Dawsari", "Majed Abdullah"], correct: 0 },
        { q: "¿Quién anotó el gol del triunfo ante Argentina en 2022?", options: ["Sami Al-Jaber", "Salem Al-Dawsari", "Saleh Al-Shehri", "Yasir Al-Shahrani"], correct: 1 },
        { q: "¿Cuál es el color principal del uniforme saudí?", options: ["Verde", "Blanco", "Dorado", "Negro"], correct: 1 },
        { q: "¿En qué confederación juega Arabia Saudita?", options: ["UEFA", "CAF", "AFC", "OFC"], correct: 2 },
        { q: "¿Quién fue el entrenador francés de Arabia en 2022?", options: ["Hervé Renard", "Zinedine Zidane", "Didier Deschamps", "Thierry Henry"], correct: 0 },
        { q: "¿Cuántas participaciones mundialistas tiene Arabia Saudita?", options: ["3", "4", "6", "8"], correct: 2 },
        { q: "¿Cuál es la ciudad capital de Arabia Saudita?", options: ["Yeda", "Riad", "La Meca", "Medina"], correct: 1 }
    ],
    "ARG": [
        { q: "¿Cuántos Mundiales ha ganado Argentina?", options: ["2", "3", "4", "5"], correct: 1 },
        { q: "¿Quién era el capitán en el título de 1986?", options: ["Mario Kempes", "Diego Maradona", "Lionel Messi", "Daniel Passarella"], correct: 1 },
        { q: "¿Contra qué país ganó la final de 1978?", options: ["Alemania", "Países Bajos", "Brasil", "Italia"], correct: 1 },
        { q: "¿Quién es su máximo goleador en Mundiales?", options: ["Gabriel Batistuta", "Lionel Messi", "Hernán Crespo", "Gonzalo Higuaín"], correct: 1 },
        { q: "¿Cómo se llamó el gol de Maradona con la mano?", options: ["El gol del siglo", "La mano de Dios", "El milagro de Diego", "Golpe de suerte"], correct: 1 },
        { q: "¿Quién metió el último penal en la final de 2022?", options: ["Gonzalo Montiel", "Ángel Di María", "Paulo Dybala", '"Dibu" Martínez'], correct: 0 },
        { q: "¿Qué portero fue el héroe de los penales en 1990?", options: ["Ubaldo Fillol", "Franco Armani", "Sergio Romero", "Sergio Goycochea"], correct: 3 },
        { q: "¿En qué año ganaron su primer Mundial?", options: ["1930", "1986", "1978", "2022"], correct: 2 },
        { q: "¿Cuál es el apodo de la selección?", options: ["La Albiceleste", "La Celeste", "Los Gauchos", "El Tango"], correct: 0 },
        { q: "¿Quién fue el director técnico en el Mundial de Qatar 2022?", options: ["Diego Maradona", "Jorge Sampaoli", "Lionel Scaloni", "Alejandro Sabella"], correct: 2 }
    ],
    "AUS": [
        { q: "¿En qué año Australia se cambió a la confederación de Asia?", options: ["1990", "2000", "2006", "2010"], correct: 2 },
        { q: "¿Cuál es el apodo oficial de la selección australiana?", options: ["Socceroos", "Wallabies", "Kangaroos", "The Aussies"], correct: 0 },
        { q: "¿Hasta qué fase llegó Australia en el Mundial de 2022?", options: ["Fase de grupos", "Octavos de final", "Cuartos", "Semifinales"], correct: 1 },
        { q: "¿Quién es el máximo goleador de Australia en los Mundiales?", options: ["Tim Cahill", "Harry Kewell", "Mark Viduka", "Mile Jedinak"], correct: 0 },
        { q: "¿Qué portero bailó en los penales contra Perú?", options: ["Maty Ryan", "Andrew Redmayne", "Mark Schwarzer", "Mitch Langerak"], correct: 1 },
        { q: "¿Cuál es el color principal del uniforme de Australia?", options: ["Rojo", "Azul", "Oro / Amarillo", "Verde"], correct: 2 },
        { q: "¿En qué Mundial debutó Australia?", options: ["1966", "1974", "1982", "1994"], correct: 1 },
        { q: "¿A qué selección eliminó Australia en el repechaje de 2006?", options: ["Uruguay", "Chile", "Perú", "Honduras"], correct: 0 },
        { q: "¿Quién es el actual capitán y portero de Australia?", options: ["Maty Ryan", "Harry Souttar", "Aaron Mooy", "Jackson Irvine"], correct: 0 },
        { q: "¿Qué país eliminó a Australia en octavos de final de 2022?", options: ["Francia", "Argentina", "Croacia", "Japón"], correct: 1 }
    ],
    "AUT": [
        { q: "¿Cuál fue la mejor posición de Austria en un Mundial?", options: ["Campeón", "Tercer Lugar (1954)", "Subcampeón", "Cuartos"], correct: 1 },
        { q: "¿Cómo se apoda a la selección austriaca?", options: ["Das Team", "Los Águilas", "Vikingos", "La Armada"], correct: 0 },
        { q: "¿Quién es su máximo goleador histórico?", options: ["Hans Krankl", "Toni Polster", "Marko Arnautovic", "David Alaba"], correct: 1 },
        { q: "¿En qué ciudad juegan usualmente de local?", options: ["Salzburgo", "Innsbruck", "Viena", "Graz"], correct: 2 },
        { q: "¿Cuál es el color principal de su primera equipación?", options: ["Azul", "Verde", "Rojo", "Amarillo"], correct: 2 },
        { q: "¿Quién es su estrella actual que jugó en el Real Madrid?", options: ["Marcel Sabitzer", "David Alaba", "Konrad Laimer", "Christoph Baumgartner"], correct: 1 },
        { q: "¿En qué año organizó Austria la Eurocopa (junto a Suiza)?", options: ["2004", "2008", "2012", "2000"], correct: 1 },
        { q: "¿Qué seleccionador alemán dirige actualmente a Austria?", options: ["Jurgen Klopp", "Ralf Rangnick", "Thomas Tuchel", "Hansi Flick"], correct: 1 },
        { q: "¿Contra quién jugaron el famoso 'Pacto de no agresión' en 1982?", options: ["Alemania", "Argelia", "Chile", "Francia"], correct: 0 },
        { q: "¿A qué confederación pertenece Austria?", options: ["CONMEBOL", "UEFA", "AFC", "CAF"], correct: 1 }
    ],
    "BEL": [
        { q: "¿Cuál es el apodo de la selección de Bélgica?", options: ["Los Diablos Rojos", "Los Leones Belgas", "La Armada Roja", "El Muro de Bruselas"], correct: 0 },
        { q: "¿Cuál fue la mejor posición de Bélgica en un Mundial?", options: ["Segundo lugar", "Tercer lugar", "Cuarto lugar", "Campeón"], correct: 1 },
        { q: "¿Qué selección eliminó a Bélgica en las semifinales de 2018?", options: ["Croacia", "Inglaterra", "Francia", "Brasil"], correct: 2 },
        { q: "¿Quién es el portero belga premiado como el mejor en 2018?", options: ["Thibaut Courtois", "Simon Mignolet", "Koen Casteels", "Jean-Marie Pfaff"], correct: 0 },
        { q: "¿Quién es el máximo asistente histórico de Bélgica?", options: ["Romelu Lukaku", "Kevin De Bruyne", "Eden Hazard", "Dries Mertens"], correct: 1 },
        { q: "¿A qué selección sudamericana eliminó Bélgica en 2018?", options: ["Brasil", "Argentina", "Uruguay", "Colombia"], correct: 0 },
        { q: "¿En qué año fue Bélgica coanfitrión de la Eurocopa?", options: ["1990", "1994", "2000", "2010"], correct: 2 },
        { q: "¿Quién es el máximo goleador histórico de Bélgica?", options: ["Romelu Lukaku", "Eden Hazard", "Marc Wilmots", "Jan Ceulemans"], correct: 0 },
        { q: "¿Contra qué país debutó Bélgica en el Mundial de 1930?", options: ["Argentina", "Brasil", "Uruguay", "Estados Unidos"], correct: 3 },
        { q: "¿Qué jugador belga era el capitán durante la 'Generación de Oro'?", options: ["Vincent Kompany", "Eden Hazard", "Jan Vertonghen", "Kevin De Bruyne"], correct: 1 }
    ],
    "BRA": [
        { q: "¿Cuál es el único país en jugar todos los Mundiales?", options: ["Alemania", "Brasil", "Italia", "Argentina"], correct: 1 },
        { q: "¿Cuántos Mundiales ha ganado Brasil?", options: ["4", "7", "6", "5"], correct: 3 },
        { q: "¿Cómo se le llamó a la derrota en la final de 1950?", options: ["El Maracanazo", "El Mineirazo", "El Azacanazo", "El Tristazo"], correct: 0 },
        { q: "¿Quién anotó dos goles en la final de 2002?", options: ["Ronaldinho", "Rivaldo", "Ronaldo (Fenómeno)", "Kaká"], correct: 2 },
        { q: "¿En qué año ganó Brasil su primer título mundial?", options: ["1958", "1950", "1962", "1970"], correct: 0 },
        { q: "¿Qué país los goleó 7-1 en el Mundial 2014?", options: ["Francia", "Alemania", "Holanda", "Bélgica"], correct: 1 },
        { q: "¿Quién es el máximo goleador histórico de la selección?", options: ["Pelé", "Zico", "Romário", "Neymar Jr"], correct: 3 },
        { q: "¿Cómo se conoce el estilo alegre de jugar de Brasil?", options: ["Tiki-taka", "Catenaccio", "Jogo Bonito", "Garra Charrua"], correct: 2 },
        { q: "¿Quién era el capitán en el Mundial de 1994?", options: ["Dunga", "Bebeto", "Cafú", "Roberto Carlos"], correct: 0 },
        { q: "¿Qué color era la camiseta de Brasil antes de 1950?", options: ["Azul", "Blanca", "Verde", "Negra"], correct: 1 }
    ],
    "CAN": [
        { q: "¿En qué país debutó Canadá en un Mundial?", options: ["México", "España", "Italia", "EE.UU."], correct: 0 },
        { q: "¿Quién es su máxima estrella actual?", options: ["Jonathan David", "Alphonso Davies", "Cyle Larin", "Atiba Hutchinson"], correct: 1 },
        { q: "¿Quién anotó el primer gol de Canadá en un Mundial?", options: ["No han anotado", "Alphonso Davies", "Junior Hoilett", "Stephen Eustáquio"], correct: 1 },
        { q: "¿Cuál es el apodo del equipo?", options: ["Los Alces", "Les Rouges", "Los Montañeses", "The Snowmen"], correct: 1 },
        { q: "¿Cuántos puntos sumaron en el Mundial 2022?", options: ["0", "1", "3", "4"], correct: 0 },
        { q: "¿En qué ciudad canadiense se jugarán partidos en 2026?", options: ["Montreal", "Toronto", "Ottawa", "Quebec"], correct: 1 },
        { q: "¿Qué símbolo aparece en su escudo?", options: ["Un castor", "Una hoja de arce", "Un oso polar", "Un copo de nieve"], correct: 1 },
        { q: "¿En qué confederación compite Canadá?", options: ["UEFA", "CONCACAF", "OFC", "CONMEBOL"], correct: 1 },
        { q: "¿Cuál es el color principal de su uniforme local?", options: ["Blanco", "Rojo", "Azul", "Negro"], correct: 1 },
        { q: "¿Qué deporte es más popular que el fútbol en Canadá?", options: ["Béisbol", "Hockey sobre hielo", "Baloncesto", "Tenis"], correct: 1 }
    ],
    "COL": [
        { q: "¿Quién anotó el único gol olímpico en un Mundial?", options: ["Marcos Coll", "James Rodríguez", "Carlos Valderrama", "Freddy Rincón"], correct: 0 },
        { q: "¿Quién fue el bota de oro en Brasil 2014?", options: ["Radamel Falcao", "Teófilo Gutiérrez", "James Rodríguez", "Jackson Martínez"], correct: 2 },
        { q: "¿Cómo se llama el portero del famoso 'Escorpión'?", options: ["David Ospina", "Oscar Córdoba", "René Higuita", "Faryd Mondragón"], correct: 2 },
        { q: "¿Cuál fue la mejor posición de Colombia en un Mundial?", options: ["Octavos", "Cuartos", "Semifinales", "Campeón"], correct: 1 },
        { q: "¿Cuál es el apodo de la selección?", options: ["Los Cafeteros", "Los Parceleros", "Los Caleños", "Los Cóndores"], correct: 0 },
        { q: "¿Quién es el jugador con melena rubia famoso de los 90?", options: ["Faustino Asprilla", "Carlos Valderrama", "Leonel Álvarez", "Adolfo Valencia"], correct: 1 },
        { q: "¿Qué país será coorganizador del Mundial 2030 con España y Portugal?", options: ["Argelia", "Egipto", "Marruecos", "Túnez"], correct: 2 },
        { q: "¿Contra qué país empató 4-4 en su primer mundial (1962)?", options: ["Unión Soviética", "Uruguay", "Yugoslavia", "Chile"], correct: 0 },
        { q: "¿Quién es el máximo goleador histórico de la selección?", options: ["James Rodríguez", "Faustino Asprilla", "Arnoldo Iguarán", "Radamel Falcao"], correct: 3 },
        { q: "¿En qué ciudad juega Colombia usualmente como local?", options: ["Bogotá", "Barranquilla", "Medellín", "Cali"], correct: 1 }
    ],
    "CIV": [
        { q: "¿Cuál es el apodo de la selección de Costa de Marfil?", options: ["Los Leones", "Las Águilas", "Los Elefantes", "Los Leopardos"], correct: 2 },
        { q: "¿Quién es el máximo goleador histórico y leyenda?", options: ["Didier Drogba", "Yaya Touré", "Salomon Kalou", "Gervinho"], correct: 0 },
        { q: "¿Cuántas veces ha ganado la Copa Africana?", options: ["1", "2", "3", "4"], correct: 2 },
        { q: "¿En qué Mundial debutó Costa de Marfil?", options: ["2006", "2002", "2010", "2014"], correct: 0 },
        { q: "¿Qué mediocampista brilló en el Manchester City?", options: ["Kolo Touré", "Yaya Touré", "Franck Kessié", "Cheick Tioté"], correct: 1 },
        { q: "¿Cuál es el color principal de su uniforme?", options: ["Naranja", "Verde", "Blanco", "Azul"], correct: 0 },
        { q: "¿En qué continente se encuentra Costa de Marfil?", options: ["Asia", "África", "Europa", "Oceanía"], correct: 1 },
        { q: "¿A qué selección derrotó en la final de la Copa Africana 2024?", options: ["Nigeria", "Egipto", "Senegal", "Marruecos"], correct: 0 },
        { q: "¿Qué delantero estrella los representa actualmente?", options: ["Nicolas Pépé", "Sébastien Haller", "Wilfried Zaha", "Max Gradel"], correct: 1 },
        { q: "¿Cuál es la ciudad más grande de Costa de Marfil?", options: ["Yamusukro", "Abiyán", "Bouaké", "Korhogo"], correct: 1 }
    ],
    "CRO": [
        { q: "¿Cuál fue la posición de Croacia en el Mundial de 2018?", options: ["Tercer lugar", "Subcampeón", "Campeón", "Cuarto lugar"], correct: 1 },
        { q: "¿Quién es el capitán y Balón de Oro de Croacia?", options: ["Luka Modrić", "Ivan Rakitić", "Mateo Kovačić", "Mario Mandžukić"], correct: 0 },
        { q: "¿A qué selección eliminó Croacia en penales en cuartos de 2022?", options: ["Argentina", "Francia", "Brasil", "Japón"], correct: 2 },
        { q: "¿En qué posición quedó Croacia en su primer Mundial (1998)?", options: ["Octavos", "Cuartos", "Tercer lugar", "Subcampeón"], correct: 2 },
        { q: "¿Cuál es el diseño característico de la camiseta?", options: ["Cuadros rojos y blancos", "Rayas verticales", "Estrellas azules", "Color sólido"], correct: 0 },
        { q: "¿Quién fue el goleador del Mundial 1998?", options: ["Davor Šuker", "Alen Bokšić", "Robert Prosinečki", "Mario Mandžukić"], correct: 0 },
        { q: "¿Qué portero croata fue figura en los penales de 2022?", options: ["Dominik Livaković", "Danijel Subašić", "Ivo Grbić", "Stipe Pletikosa"], correct: 0 },
        { q: "¿Qué país eliminó a Croacia en las semifinales de 2022?", options: ["Francia", "Argentina", "Marruecos", "Brasil"], correct: 1 },
        { q: "¿Quién es el DT que llevó a Croacia al podio en 2018 y 2022?", options: ["Zlatko Dalić", "Miroslav Blažević", "Niko Kovač", "Slaven Bilić"], correct: 0 },
        { q: "¿En qué mar tiene Croacia su costa más famosa?", options: ["Mediterráneo", "Adriático", "Negro", "Tirreno"], correct: 1 }
    ],
    "CUR": [
        { q: "¿En qué confederación juega la selección de Curazao?", options: ["CONMEBOL", "CONCACAF", "AFC", "UEFA"], correct: 1 },
        { q: "¿Cuál es el color principal de su uniforme?", options: ["Azul", "Rojo", "Verde", "Blanco"], correct: 0 },
        { q: "¿Cómo se les conoce a los habitantes y selección de Curazao?", options: ["Los Tulipanes", "La Familia Azul", "Los Isleños", "Los Piratas"], correct: 1 },
        { q: "¿Qué exjugador holandés fue su director técnico?", options: ["Patrick Kluivert", "Ruud Gullit", "Marco van Basten", "Dennis Bergkamp"], correct: 0 },
        { q: "¿Cuál es el idioma oficial de la isla junto al holandés?", options: ["Español", "Inglés", "Papiamento", "Francés"], correct: 2 },
        { q: "¿A qué reino pertenece Curazao?", options: ["Reino de España", "Reino de los Países Bajos", "Reino Unido", "Francia"], correct: 1 },
        { q: "¿Quién es uno de sus jugadores más famosos (ex-Everton)?", options: ["Cuco Martina", "Leandro Bacuna", "Tahith Chong", "Vurnon Anita"], correct: 0 },
        { q: "¿En qué mar se encuentra la isla de Curazao?", options: ["Mar Muerto", "Mar Caribe", "Océano Índico", "Mar del Norte"], correct: 1 },
        { q: "¿Ha clasificado Curazao alguna vez a un Mundial de mayores?", options: ["Sí", "Nunca", "2 veces", "En 1930"], correct: 1 },
        { q: "¿Cuál es la capital de Curazao?", options: ["Oranjestad", "Willemstad", "Kralendijk", "Philipsburg"], correct: 1 }
    ],
    "ECU": [
        { q: "¿En qué año clasificó Ecuador a su primer Mundial?", options: ["1998", "2002", "2006", "1994"], correct: 1 },
        { q: "¿Quién es el goleador histórico de Ecuador en Mundiales?", options: ["Agustín Delgado", "Felipe Caicedo", "Enner Valencia", "Alex Aguinaga"], correct: 2 },
        { q: "¿A qué fase llegó Ecuador en Alemania 2006?", options: ["Fase de Grupos", "Semifinales", "Cuartos", "Octavos"], correct: 3 },
        { q: "¿Cuál es el apodo de la selección ecuatoriana?", options: ["El Tri", "La Tricolor", "Los Amarillos", "Los Bananeros"], correct: 1 },
        { q: "¿Quién era el capitán y 10 histórico en 2002?", options: ["Alex Aguinaga", "Antonio Valencia", "Edison Méndez", "Ulises de la Cruz"], correct: 0 },
        { q: "¿Con qué país perdió Ecuador 1-0 en octavos de 2006?", options: ["Inglaterra", "Alemania", "España", "Francia"], correct: 0 },
        { q: "¿En qué país se jugó el Mundial 2022 donde estuvo Ecuador?", options: ["Rusia", "Sudáfrica", "Brasil", "Catar"], correct: 3 },
        { q: "¿Cómo se llama el estadio donde juegan en la altura de Quito?", options: ["Monumental", "Rodrigo Paz Delgado", "Capwell", "Jocay"], correct: 1 },
        { q: "¿Contra qué país debutó Ecuador en un Mundial (2002)?", options: ["Italia", "México", "Croacia", "Brasil"], correct: 0 },
        { q: "¿Quién anotó el primer gol de Ecuador en un Mundial?", options: ["Iván Kaviedes", "Carlos Tenorio", "Agustín Delgado", "Enner Valencia"], correct: 2 }
    ],
    "EGY": [
        { q: "¿Quién es el jugador egipcio más famoso de la actualidad?", options: ["Trezeguet", "Mohamed Salah", "Mohamed Elneny", "Ahmed Hegazi"], correct: 1 },
        { q: "¿En qué año participó Egipto por primera vez en un Mundial?", options: ["1934", "1970", "1990", "2018"], correct: 0 },
        { q: "¿Cuál es el apodo de la selección egipcia?", options: ["Los Leones", "Los Guerreros", "Los Zorros", "Los Faraones"], correct: 3 },
        { q: "¿Qué portero jugó un Mundial a los 45 años de edad?", options: ["Essam El-Hadary", "Mohamed El-Shenawy", "Ahmed El-Shenawy", "Sherif Ekramy"], correct: 0 },
        { q: "¿Cuántas veces ha ganado Egipto la Copa Africana?", options: ["3", "5", "7", "9"], correct: 2 },
        { q: "¿En qué país se celebró el Mundial de 1990 donde estuvo Egipto?", options: ["España", "Italia", "México", "USA"], correct: 1 },
        { q: "¿A qué confederación pertenece la selección de Egipto?", options: ["CAF", "AFC", "UEFA", "CONCACAF"], correct: 0 },
        { q: "¿Quién es el máximo goleador histórico de Egipto?", options: ["Mohamed Salah", "Hossam Hassan", "Mohamed Aboutrika", "Ahmed Hassan"], correct: 1 },
        { q: "¿Cuál es el color predominante en la camiseta de local?", options: ["Rojo", "Verde", "Blanco", "Negro"], correct: 0 },
        { q: "¿En qué ciudad egipcia se encuentra su estadio más grande?", options: ["Giza", "Alejandría", "El Cairo", "Port Said"], correct: 2 }
    ],
    "SCO": [
        { q: "¿Cuál es el apodo de la selección de Escocia?", options: ["The Lions", "The Tartan Army", "The Highlanders", "The Bravehearts"], correct: 1 },
        { q: "¿Contra qué país juega Escocia el derbi más antiguo del mundo?", options: ["Gales", "Irlanda", "Inglaterra", "Francia"], correct: 2 },
        { q: "¿Cuál es el estadio nacional de Escocia?", options: ["Hampden Park", "Celtic Park", "Ibrox", "Murrayfield"], correct: 0 },
        { q: "¿Quién es su capitán actual que juega en el Liverpool?", options: ["Scott McTominay", "Andy Robertson", "John McGinn", "Billy Gilmour"], correct: 1 },
        { q: "¿Cuál es el color principal de su uniforme?", options: ["Azul oscuro", "Rojo", "Verde", "Blanco"], correct: 0 },
        { q: "¡Qué famoso entrenador del Man. United fue escocés?", options: ["Matt Busby", "Alex Ferguson", "David Moyes", "Todos los anteriores"], correct: 3 },
        { q: "¿A cuántos Mundiales ha clasificado Escocia históricamente?", options: ["4", "8", "12", "5"], correct: 1 },
        { q: "¿Ha pasado Escocia alguna vez de la fase de grupos en un Mundial?", options: ["Sí", "Nunca", "2 veces", "En 1974"], correct: 1 },
        { q: "¿Qué flor es el símbolo de Escocia?", options: ["Rosa", "Cardo", "Trébol", "Girasol"], correct: 1 },
        { q: "¿En qué confederación compite Escocia?", options: ["CONCACAF", "UEFA", "AFC", "CAF"], correct: 1 }
    ],
    "ESP": [
        { q: "¿En qué año ganó España su único Mundial?", options: ["2006", "2008", "2010", "2012"], correct: 2 },
        { q: "¿Quién anotó el gol de la victoria en la final de 2010?", options: ["Xavi Hernández", "Andrés Iniesta", "David Villa", "Fernando Torres"], correct: 1 },
        { q: "¿Cuál es el apodo de la selección española?", options: ["La Furia Roja", "Los Matadores", "La Armada Invencible", "El Toque"], correct: 0 },
        { q: "¿Quién era el portero y capitán en Sudáfrica 2010?", options: ["Víctor Valdés", "Iker Casillas", "Pepe Reina", "David de Gea"], correct: 1 },
        { q: "¿Contra qué país perdió España en su debut de 2010?", options: ["Honduras", "Chile", "Suiza", "Portugal"], correct: 2 },
        { q: "¿En qué año organizó España el Mundial?", options: ["1978", "1996", "1992", "1982"], correct: 3 },
        { q: "¿Quién es el máximo goleador de España en Mundiales?", options: ["David Villa", "Raúl González", "Fernando Morientes", "Álvaro Morata"], correct: 0 },
        { q: "¿A qué selección golearon 7-0 en el Mundial de 2022?", options: ["Alemania", "Costa Rica", "Japón", "Marruecos"], correct: 1 },
        { q: "¿Cómo se llamaba la mascota del Mundial España 82?", options: ["Juanito", "Footix", "Piqué", "Naranjito"], correct: 3 },
        { q: "¿Quién era el entrenador cuando ganaron el Mundial?", options: ["Luis Aragonés", "Pep Guardiola", "Vicente del Bosque", "Luis Enrique"], correct: 2 }
    ],
    "USA": [
        { q: "¿En qué año organizaron su primer Mundial?", options: ["1990", "1994", "2002", "1982"], correct: 1 },
        { q: "¿Cuál es el apodo oficial del equipo masculino?", options: ["The Eagles", "The Stars and Stripes", "The Soccer Kings", "The Dream Team"], correct: 1 },
        { q: "¿Quién es su goleador histórico en Mundiales?", options: ["Christian Pulisic", "Landon Donovan", "Clint Dempsey", "Alexi Lalas"], correct: 1 },
        { q: "¿A qué país eliminaron en octavos de final en 2002?", options: ["Alemania", "México", "Italia", "Japón"], correct: 1 },
        { q: "¿Cuál fue su posición histórica en el Mundial de 1930?", options: ["Primer lugar", "Segundo lugar", "Tercer lugar", "Octavo lugar"], correct: 2 },
        { q: "¿Cómo llaman ellos oficialmente al fútbol?", options: ["Football", "Soccer", "Kickball", "Rugby"], correct: 1 },
        { q: "¿En qué ciudad se jugó la final de 1994?", options: ["Nueva York", "Miami", "Pasadena", "Chicago"], correct: 2 },
        { q: "¿Quién es su actual estrella que juega en el AC Milan?", options: ["Tim Weah", "Weston McKennie", "Christian Pulisic", "Gio Reyna"], correct: 2 },
        { q: "¿Qué selección los eliminó en Qatar 2022?", options: ["Inglaterra", "Países Bajos", "Francia", "Argentina"], correct: 1 },
        { q: "¿Cuántas ciudades sede tendrá EE.UU. en 2026?", options: ["5", "8", "11", "15"], correct: 2 }
    ],
    "FRA": [
        { q: "¿En qué año ganó Francia su primer Mundial siendo anfitrión?", options: ["1982", "1998", "2006", "2018"], correct: 1 },
        { q: "¿Quién es el jugador francés con más goles en finales de Mundiales?", options: ["Zinedine Zidane", "Thierry Henry", "Kylian Mbappé", "Just Fontaine"], correct: 2 },
        { q: "¿Qué selección eliminó a Francia en la final de 2022?", options: ["Argentina", "Italia", "Marruecos", "Brasil"], correct: 0 },
        { q: "¿Quién era el capitán de Francia en el título de 1998?", options: ["Patrick Vieira", "Didier Deschamps", "Michel Platini", "Eric Cantona"], correct: 1 },
        { q: "¿Cuántos goles anotó Just Fontaine en el Mundial de 1958 (récord histórico)?", options: ["10", "15", "13", "9"], correct: 2 },
        { q: "¿En qué Mundial Francia quedó fuera en fase de grupos siendo el campeón vigente?", options: ["2010", "2002", "1994", "2014"], correct: 1 },
        { q: "¿Cómo se le apoda a la selección francesa?", options: ["Les Bleus", "La Tri", "Los Galos", "El Gallo Rojo"], correct: 0 },
        { q: "¿En qué ciudad se jugó la final de Francia 98?", options: ["Marsella", "Lyon", "Niza", "Saint-Denis"], correct: 3 },
        { q: "¿Qué jugador francés fue expulsado en la final de 2006 por un cabezazo?", options: ["Franck Ribéry", "Zinedine Zidane", "Fabien Barthez", "Lilian Thuram"], correct: 1 },
        { q: "¿Quién es el actual director técnico de Francia (en 2026)?", options: ["Arsène Wenger", "Zinedine Zidane", "Didier Deschamps", "Thierry Henry"], correct: 2 }
    ],
    "ALE": [
        { q: "¿Cuántas veces ha ganado Alemania la Copa del Mundo?", options: ["3", "4", "5", "2"], correct: 1 },
        { q: "¿Quién es el máximo goleador histórico de los Mundiales (alemán)?", options: ["Gerd Müller", "Thomas Müller", "Miroslav Klose", "Oliver Bierhoff"], correct: 2 },
        { q: "¿Qué país fue la sede cuando Alemania ganó su último Mundial en 2014?", options: ["Alemania", "Sudáfrica", "Brasil", "Rusia"], correct: 2 },
        { q: "¿Cuál es el apodo más común de la selección alemana?", options: ["Die Mannschaft", "Los Panzer", "El Águila Negra", "La Maquinaria"], correct: 0 },
        { q: "¿Qué portero alemán fue elegido el mejor jugador (Balón de Oro) en 2002?", options: ["Manuel Neuer", "Jens Lehmann", "Oliver Kahn", "Sepp Maier"], correct: 2 },
        { q: "¿Contra qué país ganó Alemania la final del Mundial 1990?", options: ["Países Bajos", "Argentina", "Italia", "Inglaterra"], correct: 1 },
        { q: "¿En qué año organizó Alemania su Mundial más reciente?", options: ["1974", "1990", "2002", "2006"], correct: 3 },
        { q: "¿Quién anotó el gol de la victoria en la final de 2014 contra Argentina?", options: ["Mario Götze", "Mesut Özil", "Toni Kroos", "Bastian Schweinsteiger"], correct: 0 },
        { q: "¿Qué equipo derrotó a Alemania en la final de su propio mundial en 1966?", options: ["Brasil", "Italia", "Inglaterra", "Uruguay"], correct: 2 },
        { q: "¿Quién fue el entrenador de Alemania en el título de 2014?", options: ["Jürgen Klinsmann", "Joachim Löw", "Hansi Flick", "Julian Nagelsmann"], correct: 1 }
    ],
    "GHA": [
        { q: "¿Cuál es el apodo de la selección de Ghana?", options: ["Las Águilas Verdes", "Black Stars", "Los Faraones", "Los Leopardos"], correct: 1 },
        { q: "¿Qué selección eliminó a Ghana en los cuartos de 2010 tras un penal fallado?", options: ["Uruguay", "Brasil", "Holanda", "Alemania"], correct: 0 },
        { q: "¿Quién es el máximo goleador histórico de Ghana?", options: ["André Ayew", "Asamoah Gyan", "Abedi Pelé", "Thomas Partey"], correct: 1 },
        { q: "¿En qué año debutó Ghana en una Copa del Mundo?", options: ["1990", "1998", "2006", "2010"], correct: 2 },
        { q: "¿A qué potencia europea derrotó Ghana en el Mundial de 2006?", options: ["República Checa", "Italia", "Francia", "España"], correct: 0 },
        { q: "¿Cuál es el color que predomina en su bandera y uniforme local?", options: ["Verde", "Blanco", "Azul", "Negro"], correct: 1 },
        { q: "¿Quién es el actual mediocampista estrella que juega en el Arsenal?", options: ["Jordan Ayew", "Mohammed Kudus", "Thomas Partey", "Iñaki Williams"], correct: 2 },
        { q: "¿Qué jugador de origen español decidió representar a Ghana en 2022?", options: ["Iñaki Williams", "Nico Williams", "Ansu Fati", "Alejandro Balde"], correct: 0 },
        { q: "¿Cuántas veces ha ganado Ghana la Copa Africana de Naciones?", options: ["2", "3", "4", "6"], correct: 2 },
        { q: "¿En qué ciudad se encuentra el estadio nacional de Ghana?", options: ["Acra", "Kumasi", "Tamale", "Sekondi"], correct: 0 }
    ],
    "HAI": [
        { q: "¿Cuál es el apodo de la selección de Haití?", options: ["Los Bicolores", "Los Granaderos", "Águilas Azules", "Los Piratas"], correct: 1 },
        { q: "¿En qué año participó Haití en su único Mundial?", options: ["1970", "1974", "1982", "1990"], correct: 1 },
        { q: "¿Quién anotó el famoso gol de Haití contra Italia en 1974?", options: ["Emmanuel Sanon", "Philippe Vorbe", "Henri Francillon", "Guy Saint-Vil"], correct: 0 },
        { q: "¿Cuál es el color principal de su uniforme?", options: ["Rojo y Azul", "Verde", "Blanco", "Amarillo"], correct: 0 },
        { q: "¿A qué confederación pertenece Haití?", options: ["CONMEBOL", "CONCACAF", "CAF", "UEFA"], correct: 1 },
        { q: "¿Cuál es la capital de Haití?", options: ["Cabo Haitiano", "Puerto Príncipe", "Les Cayes", "Jacmel"], correct: 1 },
        { q: "¿Cómo se llama su estadio nacional?", options: ["Sylvio Cator", "Estadio Azteca", "Estadio Nacional", "La Bomboneira"], correct: 0 },
        { q: "¿A qué histórico portero italiano le quitó el invicto Haití en 1974?", options: ["Dino Zoff", "Walter Zenga", "Gianluigi Buffon", "Enrico Albertosi"], correct: 0 },
        { q: "¿Cuál es el idioma principal hablado en Haití junto al francés?", options: ["Inglés", "Español", "Criollo haitiano", "Portugués"], correct: 2 },
        { q: "¿Qué isla comparte Haití con la Rep. Dominicana?", options: ["Cuba", "La Española", "Jamaica", "Puerto Rico"], correct: 1 }
    ],
    "ING": [
        { q: "¿En qué año ganó Inglaterra su único Mundial?", options: ["1966", "1970", "1990", "1954"], correct: 0 },
        { q: "¿Cómo se llama el estadio donde Inglaterra juega sus partidos de local?", options: ["Old Trafford", "Anfield", "Wembley", "Stamford Bridge"], correct: 2 },
        { q: "¿Cuál es el apodo de la selección inglesa?", options: ["The Lions", "The Three Lions", "The Warriors", "The Royals"], correct: 1 },
        { q: "¿Quién fue el capitán de Inglaterra en el Mundial de 1966?", options: ["Bobby Charlton", "Bobby Moore", "Geoff Hurst", "Gordon Banks"], correct: 1 },
        { q: "¿Qué jugador inglés fue el goleador del Mundial de México 1986?", options: ["Gary Lineker", "Harry Kane", "David Beckham", "Alan Shearer"], correct: 0 },
        { q: "¿A qué selección eliminó Inglaterra en la final de 1966?", options: ["Portugal", "Argentina", "Brasil", "Alemania Federal"], correct: 3 },
        { q: "¿Quién anotó el primer hat-trick en una final de Copa del Mundo?", options: ["Pelé", "Geoff Hurst", "Gerd Müller", "Kylian Mbappé"], correct: 1 },
        { q: "¿Qué estrella inglesa falló un penal clave en Qatar 2022?", options: ["Phil Foden", "Bukayo Saka", "Harry Kane", "Jude Bellingham"], correct: 2 },
        { q: "¿Contra qué país perdió Inglaterra en el partido de la 'Mano de Dios'?", options: ["Argentina", "Alemania", "Escocia", "Italia"], correct: 0 },
        { q: "¿Cuál es la liga profesional de Inglaterra?", options: ["Championship", "League One", "Premier League", "FA Cup"], correct: 2 }
    ],
    "CPV": [
        { q: "¿Cuál es el apodo de la selección de Cabo Verde?", options: ["Los Tiburones Azules", "Los Leones", "Las Águilas", "Los Halcones"], correct: 0 },
        { q: "¿En qué continente se encuentra Cabo Verde?", options: ["Europa", "África", "América", "Oceanía"], correct: 1 },
        { q: "¿Cuál es el idioma oficial de Cabo Verde?", options: ["Español", "Francés", "Portugués", "Inglés"], correct: 2 },
        { q: "¿A qué fase llegó Cabo Verde en la Copa Africana 2024?", options: ["Fase de Grupos", "Octavos", "Cuartos de final", "Final"], correct: 2 },
        { q: "¿Cuál es el color principal de su uniforme?", options: ["Azul", "Rojo", "Verde", "Amarillo"], correct: 0 },
        { q: "¿En qué océano se encuentra el archipiélago de Cabo Verde?", options: ["Índico", "Atlántico", "Pacífico", "Ártico"], correct: 1 },
        { q: "¿Qué exjugador del Man. United tiene raíces caboverdianas?", options: ["Cristiano Ronaldo", "Nani", "Bruno Fernandes", "Luis Figo"], correct: 1 },
        { q: "¿Cuál es la capital de Cabo Verde?", options: ["Mindelo", "Praia", "Sal", "Espargos"], correct: 1 },
        { q: "¿Ha clasificado Cabo Verde alguna vez a un Mundial de la FIFA?", options: ["Sí", "Nunca", "2 veces", "En 2010"], correct: 1 },
        { q: "¿A qué confederación pertenece?", options: ["UEFA", "AFC", "CAF", "CONMEBOL"], correct: 2 }
    ],
    "JPN": [
        { q: "¿Cuál es el apodo de la selección japonesa?", options: ["Los Guerreros", "Samurái Blue", "El Sol Naciente", "Los Dragones Azules"], correct: 1 },
        { q: "¿En qué año organizó Japón el Mundial?", options: ["1998", "2002", "2006", "1994"], correct: 1 },
        { q: "¿A qué potencias derrotó Japón en la fase de grupos de 2022?", options: ["Alemania y España", "Francia e Italia", "Inglaterra y Bélgica", "Portugal y Holanda"], correct: 0 },
        { q: "¿A qué fase ha llegado Japón como máximo?", options: ["Cuartos de final", "Octavos de final", "Semifinales", "Fase de grupos"], correct: 1 },
        { q: "¿Qué selección eliminó a Japón en penales en 2022?", options: ["Brasil", "Bélgica", "Croacia", "España"], correct: 2 },
        { q: "¿Quién es el máximo goleador histórico de Japón?", options: ["Kamamoto", "Keisuke Honda", "Shinji Kagawa", "Hidetoshi Nakata"], correct: 0 },
        { q: "¿Qué jugador japonés es famoso por jugar en el Mónaco?", options: ["Maya Yoshida", "Takefusa Kubo", "Kaoru Mitoma", "Wataru Endo"], correct: 1 },
        { q: "¿Cuál es el color principal del uniforme de Japón?", options: ["Rojo", "Blanco", "Azul", "Verde"], correct: 2 },
        { q: "¿Quién anotó el gol de la victoria contra Alemania en 2022?", options: ["Takuma Asano", "Ritsu Doan", "Daichi Kamada", "Daizen Maeda"], correct: 0 },
        { q: "¿En qué confederación juega Japón?", options: ["OFC", "AFC (Asia)", "UEFA", "CONCACAF"], correct: 1 }
    ],
    "JOR": [
        { q: "¿Cuál es el apodo de la selección de Jordania?", options: ["Los Valientes", "Los Nashama", "Los Halcones", "Los Leones del Desierto"], correct: 1 },
        { q: "¿A qué final histórica llegó Jordania en 2024?", options: ["Copa del Mundo", "Copa de Asia", "Copa Árabe", "Juegos Olímpicos"], correct: 1 },
        { q: "¿Cuál es el color principal de su uniforme?", options: ["Blanco", "Rojo", "Verde", "Negro"], correct: 0 },
        { q: "¿Cuál es la capital de Jordania?", options: ["Ammán", "Aqaba", "Petra", "Irbid"], correct: 0 },
        { q: "¿En qué confederación compite Jordania?", options: ["CAF", "UEFA", "AFC", "OFC"], correct: 2 },
        { q: "¿Quién es su estrella actual que juega en Francia (Montpellier)?", options: ["Mousa Al-Tamari", "Yazan Al-Naimat", "Hamza Al-Dardour", "Amer Shafi"], correct: 0 },
        { q: "¿Contra qué selección perdió la final de la Copa de Asia 2024?", options: ["Catar", "Japón", "Corea del Sur", "Irán"], correct: 0 },
        { q: "¿En qué continente se ubica Jordania?", options: ["África", "Europa", "Asia", "Oceanía"], correct: 2 },
        { q: "¿Cómo se llama su estadio más importante?", options: ["Estadio Internacional de Ammán", "Estadio Rey Abdullah", "Estadio Al-Bayt", "Estadio de Lusail"], correct: 0 },
        { q: "¿Ha clasificado Jordania alguna vez a un Mundial de mayores?", options: ["Sí", "Nunca", "En 2014", "En 1990"], correct: 1 }
    ],
    "KOR": [
        { q: "¿Cuál fue la mejor posición de Corea del Sur en un Mundial?", options: ["Tercer lugar", "Cuarto lugar", "Octavos de final", "Cuartos de final"], correct: 1 },
        { q: "¿Cuál es el apodo de la selección surcoreana?", options: ["Guerreros Taeguk", "Tigres de Seúl", "Dragones Rojos", "Ejército Rojo"], correct: 0 },
        { q: "¿A qué selección eliminó Corea en octavos de 2002?", options: ["España", "Italia", "Alemania", "Portugal"], correct: 1 },
        { q: "¿Quién es el capitán que juega en el Tottenham?", options: ["Park Ji-sung", "Son Heung-min", "Kim Min-jae", "Lee Kang-in"], correct: 1 },
        { q: "¿Qué selección eliminó a Corea del Sur en octavos de 2022?", options: ["Brasil", "Uruguay", "Portugal", "Ghana"], correct: 0 },
        { q: "¡A qué potencia europea derrotó Corea 2-0 en 2018?", options: ["Italia", "Francia", "Alemania", "Inglaterra"], correct: 2 },
        { q: "¿Quién fue el DT que llevó a Corea a semis en 2002?", options: ["Guus Hiddink", "Dick Advocaat", "Bert van Marwijk", "Louis van Gaal"], correct: 0 },
        { q: "¿En qué año debutó Corea del Sur en un Mundial?", options: ["1930", "1954", "1986", "2002"], correct: 1 },
        { q: "¿Cuál es el color principal de su uniforme?", options: ["Rojo", "Azul", "Blanco", "Amarillo"], correct: 0 },
        { q: "¿Quién es el defensa que destacó en el Napoli y Bayern?", options: ["Son Heung-min", "Kim Min-jae", "Hwang Hee-chan", "Cho Gue-sung"], correct: 1 }
    ],
    "MAR": [
        { q: "¿Qué hito histórico logró Marruecos en Qatar 2022?", options: ["Primer árabe en ganar", "Primera africana en semifinales", "Más goles anotados", "Eliminar a Brasil"], correct: 1 },
        { q: "¿Qué selección eliminó a Marruecos en las semifinales de 2022?", options: ["Argentina", "España", "Francia", "Portugal"], correct: 2 },
        { q: "¿A qué selección europea eliminó Marruecos en penales en 2022?", options: ["España", "Portugal", "Bélgica", "Alemania"], correct: 0 },
        { q: "¿Cuál es el apodo de la selección de Marruecos?", options: ["Los Faraones", "Los Leones del Atlas", "Águilas de Cartago", "Zorros del Desierto"], correct: 1 },
        { q: "¿Quién es el portero marroquí que fue figura en 2022?", options: ["Munir Mohamedi", "Yassine Bounou (Bono)", "Reda Tagnaouti", "Zaki Badou"], correct: 1 },
        { q: "¿En qué Mundial Marruecos fue el primero de África en pasar a octavos?", options: ["México 86", "España 82", "Italia 90", "Francia 98"], correct: 0 },
        { q: "¿Quién es el lateral estrella que juega en el PSG?", options: ["Noussair Mazraoui", "Achraf Hakimi", "Nayef Aguerd", "Romain Saïss"], correct: 1 },
        { q: "¿Qué país será coorganizador del Mundial 2030 con España y Portugal?", options: ["Argelia", "Egipto", "Marruecos", "Túnez"], correct: 2 },
        { q: "¿Quién es el entrenador que los llevó a semis en 2022?", options: ["Walid Regragui", "Hervé Renard", "Vahid Halilhodžić", "Badou Ezzaki"], correct: 0 },
        { q: "¿En qué continente se encuentra Marruecos?", options: ["Asia", "África", "Europa", "Oceanía"], correct: 1 }
    ],
    "MEX": [
        { q: "¿En qué año fue su primer Mundial como sede?", options: ["1970", "1986", "1967", "19576"], correct: 0 },
        { q: "¿Cómo se llama su estadio más emblemático?", options: ["Estadio Jalisco", "Estadio BBVA", "Estadio Azteca", "El volcán"], correct: 2 },
        { q: "¿Quién es su máximo goleador en Mundiales?", options: ["Hugo Sánchez", "Luis Hernández", "Chicharito", "Giovani Dos Santos"], correct: 2 },
        { q: "¿A qué fase no han podido pasar desde 1994 (hasta 2022)?", options: ["Semifinales", "Octavos", "Clasificación", "Cuartos de final"], correct: 3 },
        { q: "¿Qué apodo recibe la selección mexicana?", options: ["Las águilas", "La raya", "El Tri", "Los chidos"], correct: 2 },
        { q: "¿Contra qué país jugó el partido inaugural en 1970?", options: ["Brasil", "Unión Soviética", "Italia", "El Salvador"], correct: 1 },
        { q: "¿Quién es el capitán que jugó 5 mundiales distintos?", options: ["Rafael Márquez", "Guillermo Ochoa", "Carlos Vela", "Oribe Peralta"], correct: 0 },
        { q: "¿En qué ciudad mexicana se encuentra el Estadio BBVA?", options: ["CDMX", "Guadalajara", "Monterrey", "Puebla"], correct: 2 },
        { q: "¿Qué era 'Pique', la mascota de 1986?", options: ["Un perro", "Un chile", "Un jaguar", "Un taco"], correct: 1 },
        { q: "¿Cuál es el mejor puesto histórico de México?", options: ["Campeón", "Cuarto lugar", "Sexto lugar", "Subcampeón"], correct: 2 }
    ],
    "NOR": [
        { q: "¿Quién es el delantero estrella de Noruega actualmente?", options: ["Martin Ødegaard", "Erling Haaland", "Alexander Sørloth", "Joshua King"], correct: 1 },
        { q: "¿Cuál es el apodo de la selección noruega?", options: ["Los Vikingos", "Løvene (Los Leones)", "La Armada Roja", "Los Osos Polares"], correct: 1 },
        { q: "¿Quién es el capitán y mediocampista del Arsenal?", options: ["Erling Haaland", "Martin Ødegaard", "Sander Berge", "Julian Ryerson"], correct: 1 },
        { q: "¿Cuál fue la mejor posición de Noruega en un Mundial?", options: ["Cuartos", "Octavos (1998)", "Fase de grupos", "Semifinales"], correct: 1 },
        { q: "¿A qué selección campeona del mundo venció Noruega en 1998?", options: ["Alemania", "Brasil", "Francia", "Italia"], correct: 1 },
        { q: "¿En qué confederación compite Noruega?", options: ["UEFA", "AFC", "CONCACAF", "CONMEBOL"], correct: 0 },
        { q: "¿Cuál es el color principal de su uniforme?", options: ["Azul", "Blanco", "Rojo", "Verde"], correct: 2 },
        { q: "¿En qué país se celebró el Mundial de 1994 donde estuvo Noruega?", options: ["Francia", "Italia", "USA", "México"], correct: 2 },
        { q: "¿Cuál es la capital de Noruega?", options: ["Bergen", "Oslo", "Stavanger", "Trondheim"], correct: 1 },
        { q: "¿Qué animal aparece en el escudo de la federación?", options: ["Oso", "León", "Águila", "Lobo"], correct: 1 }
    ],
    "NZL": [
        { q: "¿Cuál es el apodo de la selección de Nueva Zelanda?", options: ["All Blacks", "All Whites", "The Kiwis", "Island Warriors"], correct: 1 },
        { q: "¿En qué Mundial terminó Nueva Zelanda invicta pero eliminada?", options: ["1982", "2010", "2014", "2022"], correct: 1 },
        { q: "¿En qué confederación juega Nueva Zelanda?", options: ["AFC", "UEFA", "OFC (Oceanía)", "CONCACAF"], correct: 2 },
        { q: "¿Cuál es el color principal de su uniforme de local?", options: ["Negro", "Blanco", "Azul", "Verde"], correct: 1 },
        { q: "¿A qué selección sudamericana enfrentó en el repechaje para 2018?", options: ["Perú", "Uruguay", "Chile", "Colombia"], correct: 0 },
        { q: "¿Qué baile tradicional realizan antes de algunos partidos?", options: ["Samba", "Haka", "Sirtaki", "Flamenco"], correct: 1 },
        { q: "¿Cuál es la capital de Nueva Zelanda?", options: ["Auckland", "Wellington", "Christchurch", "Queenstown"], correct: 1 },
        { q: "¿Quién es su delantero histórico (ex-Burnley y Newcastle)?", options: ["Chris Wood", "Shane Smeltz", "Ryan Nelsen", "Winston Reid"], correct: 0 },
        { q: "¿Cuántos Mundiales de mayores ha jugado Nueva Zelanda?", options: ["1", "2", "3", "Ninguno"], correct: 1 },
        { q: "¿Contra qué país empató 1-1 en el Mundial 2010?", options: ["Italia", "Paraguay", "Eslovaquia", "Todas las anteriores"], correct: 3 }
    ],
    "NED": [
        { q: "¿Cuántas finales de Copa del Mundo ha perdido Países Bajos?", options: ["2", "3", "1", "4"], correct: 1 },
        { q: "¿Qué apodo recibió la selección de 1974?", options: ["La Naranja Mecánica", "Los Tulipanes de Hierro", "El Rayo Naranja", "El Reloj Holandés"], correct: 0 },
        { q: "¿Quién es el máximo exponente del 'Fútbol Total'?", options: ["Marco van Basten", "Johan Cruyff", "Arjen Robben", "Ruud Gullit"], correct: 1 },
        { q: "¿Contra qué país perdió la final del Mundial de Sudáfrica 2010?", options: ["Alemania", "Brasil", "España", "Argentina"], correct: 2 },
        { q: "¿Cuál es el color característico de su uniforme?", options: ["Naranja", "Rojo", "Blanco", "Azul"], correct: 0 },
        { q: "¿Quién anotó el gol de cabeza 'volador' contra España en 2014?", options: ["Wesley Sneijder", "Robin van Persie", "Arjen Robben", "Memphis Depay"], correct: 1 },
        { q: "¿En qué Mundial llegaron a la final consecutivamente (años 70)?", options: ["1970 y 1974", "1974 y 1978", "1978 y 1982", "1966 y 1970"], correct: 1 },
        { q: "¿Qué selección eliminó a Holanda en las semis de 2014?", options: ["Argentina", "Alemania", "Brasil", "Chile"], correct: 0 },
        { q: "¿Quién era el entrenador de Países Bajos en Qatar 2022?", options: ["Ronald Koeman", "Louis van Gaal", "Frank de Boer", "Guus Hiddink"], correct: 1 },
        { q: "¿Cómo se llama el estadio más grande de Países Bajos?", options: ["Philips Stadion", "De Kuip", "Johan Cruyff ArenA", "GelreDome"], correct: 2 }
    ],
    "PAN": [
        { q: "¿En qué año participó Panamá en su primer Mundial masculino?", options: ["2014", "2018", "2022", "2010"], correct: 1 },
        { q: "¿Cuál es el apodo de la selección panameña?", options: ["La Roja", "La Marea", "Los Canaleros", "El Istmo"], correct: 2 },
        { q: "¿Quién anotó el primer gol de Panamá en un Mundial?", options: ["Felipe Baloy", "Luis Tejada", "Blas Pérez", "Román Torres"], correct: 0 },
        { q: "¿Qué jugador anotó el gol de la clasificación a Rusia?", options: ["Luis Tejada", "Gabriel Torres", "Aníbal Godoy", "Román Torres"], correct: 3 },
        { q: "¿Cuál es el color principal del uniforme de local?", options: ["Azul", "Rojo", "Blanco", "Amarillo"], correct: 1 },
        { q: "¿En qué confederación juega Panamá?", options: ["CONMEBOL", "CONCACAF", "UEFA", "AFC"], correct: 1 },
        { q: "¿Quién es el máximo goleador histórico (fallecido en 2024)?", options: ["Luis Tejada", "Blas Pérez", "Roberto Brown", "Julio Dely Valdés"], correct: 0 },
        { q: "¿Quién es el actual director técnico de Panamá?", options: ["Hernán Darío Gómez", "Julio Dely Valdés", "Thomas Christiansen", "Gary Stempel"], correct: 2 },
        { q: "¿Cómo se llama el estadio principal en Ciudad de Panamá?", options: ["Estadio Nacional", "Estadio Rommel Fernández", "Estadio Rod Carew", "Estadio Maracaná"], correct: 1 },
        { q: "¿En qué parte del continente americano se encuentra?", options: ["Sudamérica", "Norteamérica", "Centroamérica", "Las Antillas"], correct: 2 }
    ],
    "PAR": [
        { q: "¿Cuál fue la mejor marca de Paraguay en un Mundial (2010)?", options: ["Octavos", "Final", "Semifinales", "Cuartos"], correct: 3 },
        { q: "¿Quién es el portero que pateaba tiros libres y penales?", options: ["Justo Villar", "José Luis Chilavert", "Roberto Fernández", "Antony Silva"], correct: 1 },
        { q: "¿Qué país eliminó a Paraguay en los penales de 2010?", options: ["Alemania", "Japón", "Italia", "España"], correct: 3 },
        { q: "¿Cuál es el apodo de la selección paraguaya?", options: ["La Albirroja", "La Rojiblanca", "Los Guaraníes", "La Garra"], correct: 0 },
        { q: "¿Quién es su máximo goleador histórico?", options: ["Salvador Cabañas", "José Cardozo", "Roque Santa Cruz", "Nelson Haedo Valdez"], correct: 2 },
        { q: "¿En qué año fue su primera participación mundialista?", options: ["1958", "1950", "1930", "1986"], correct: 2 },
        { q: "¿Qué selección los eliminó con 'Gol de Oro' en 1998?", options: ["Brasil", "Francia", "Nigeria", "Bulgaria"], correct: 1 },
        { q: "¿Cuántos Mundiales seguidos jugó entre 1998 y 2010?", options: ["2", "3", "5", "4"], correct: 3 },
        { q: "¿Quién era el DT en el Mundial de Sudáfrica?", options: ["Tata Martino", "Chilavert", "Francisco Arce", "Ramón Díaz"], correct: 0 },
        { q: "¿Cómo se llama el estadio principal de Paraguay?", options: ["La Nueva Olla", "Feliciano Cáceres", "Manuel Ferreira", "Defensores del Chaco"], correct: 3 }
    ],
    "POR": [
        { q: "¿Quién es el máximo goleador histórico de Portugal en Mundiales?", options: ["Eusébio", "Cristiano Ronaldo", "Pauleta", "Luís Figo"], correct: 0 },
        { q: "¿En qué año alcanzó Portugal su mejor posición (3er lugar)?", options: ["2006", "1966", "2022", "1990"], correct: 1 },
        { q: "¿Cuántos Mundiales ha jugado Cristiano Ronaldo?", options: ["4", "5", "3", "6"], correct: 1 },
        { q: "¿Cuál es el apodo de la selección portuguesa?", options: ["La Roja", "Los Navegantes", "Seleção das Quinas", "El Equipo de Oro"], correct: 2 },
        { q: "¿Quién era el capitán de Portugal en el Mundial de 2006?", options: ["Cristiano Ronaldo", "Luís Figo", "Deco", "Ricardo Carvalho"], correct: 1 },
        { q: "¿Qué país eliminó a Portugal en las semifinales de 2006?", options: ["Francia", "Italia", "Alemania", "Brasil"], correct: 0 },
        { q: "¿Contra qué selección debutó Portugal en el Mundial de 1966?", options: ["Brasil", "Bulgaria", "Hungría", "Corea del Norte"], correct: 2 },
        { q: "¿Qué jugador portugués anotó 9 goles en un solo Mundial (1966)?", options: ["Cristiano Ronaldo", "Gonçalo Ramos", "Eusébio", "Nani"], correct: 2 },
        { q: "¿En qué confederación compite Portugal?", options: ["CONMEBOL", "AFC", "UEFA", "CAF"], correct: 2 },
        { q: "¿Cuál es el color principal del uniforme de Portugal?", options: ["Azul", "Blanco", "Rojo (granate)", "Verde"], correct: 2 }
    ],
    "QAT": [
        { q: "¿En qué año organizó Catar la Copa del Mundo?", options: ["2018", "2022", "2026", "2014"], correct: 1 },
        { q: "¿Cuál es el apodo de la selección de Catar?", options: ["Al-Annabi", "Los Halcones", "Los Leones", "Los Caballeros"], correct: 0 },
        { q: "¿En qué año ganó Catar la Copa de Asia por primera vez?", options: ["2015", "2023", "2019", "2011"], correct: 2 },
        { q: "¿Quién es el máximo goleador histórico de Catar?", options: ["Akram Afif", "Hassan Al-Haydos", "Mansour Muftah", "Almoez Ali"], correct: 3 },
        { q: "¿Cuál es el color característico del uniforme de Catar?", options: ["Rojo sangre", "Granate (Marrón)", "Blanco total", "Verde oscuro"], correct: 1 },
        { q: "¿En qué estadio se jugó la gran final del Mundial 2022?", options: ["Estadio de Lusail", "Estadio Al Bayt", "Estadio 974", "Estadio Al Thumama"], correct: 0 },
        { q: "¿Qué estrella de Catar fue el mejor de la Copa de Asia 2023?", options: ["Almoez Ali", "Akram Afif", "Saad Al Sheeb", "Bassam Al-Rawi"], correct: 1 },
        { q: "¿Cuántos puntos sumó Catar en la fase de grupos de 2022?", options: ["1", "3", "4", "0"], correct: 3 },
        { q: "¿Cuál es la ciudad capital de Catar?", options: ["Al Wakrah", "Lusail", "Doha", "Al Rayyan"], correct: 2 }
    ],
    "IRN": [
        { q: "¿Cuál es el apodo oficial de la selección de Irán?", options: ["Leones de Persia", "Team Melli", "Los Halcones", "Príncipes del Desierto"], correct: 1 },
        { q: "¿Quién es el máximo goleador histórico de Irán?", options: ["Sardar Azmoun", "Mehdi Taremi", "Ali Daei", "Ali Karimi"], correct: 2 },
        { q: "¿En qué Mundial logró Irán su victoria contra EE.UU. (2-1)?", options: ["1994", "1998", "2006", "2014"], correct: 1 },
        { q: "¿A qué selección europea derrotó Irán en Qatar 2022?", options: ["Inglaterra", "Escocia", "Dinamarca", "Gales"], correct: 3 },
        { q: "¿Quién es el delantero estrella actual que juega en el Inter?", options: ["Mehdi Taremi", "Sardar Azmoun", "Saman Ghoddos", "Alireza Jahanbakhsh"], correct: 0 },
        { q: "¿Cuál es el color principal del uniforme de local de Irán?", options: ["Rojo", "Verde", "Blanco", "Amarillo"], correct: 2 },
        { q: "¿En qué confederación compite la selección de Irán?", options: ["UEFA", "AFC", "CAF", "OFC"], correct: 1 },
        { q: "¿Qué animal aparece en la indumentaria de Irán?", options: ["León", "Águila", "Tigre", "Guepardo asiático"], correct: 3 },
        { q: "¿Qué entrenador dirigió a Irán en 2014, 2018 y 2022?", options: ["Ali Daei", "Carlos Queiroz", "Dragan Skocic", "Branko Ivankovic"], correct: 1 },
        { q: "¿Cuál es la capital de Irán?", options: ["Teherán", "Isfahán", "Shiraz", "Tabriz"], correct: 0 }
    ],
    "SEN": [
        { q: "¿En qué año debutó Senegal ganándole al campeón vigente (Francia)?", options: ["1998", "2002", "2010", "2018"], correct: 1 },
        { q: "¿Cuál es el apodo de la selección de Senegal?", options: ["Leones de la Teranga", "Águilas Verdes", "Los Elefantes", "Estrellas Negras"], correct: 0 },
        { q: "¿A qué fase llegó Senegal en su histórico debut en 2002?", options: ["Octavos de final", "Semifinales", "Cuartos de final", "Final"], correct: 2 },
        { q: "¿Quién es la máxima estrella actual de Senegal?", options: ["Kalidou Koulibaly", "Édouard Mendy", "Idrissa Gueye", "Sadio Mané"], correct: 3 },
        { q: "¿Qué país eliminó a Senegal en el Mundial de Qatar 2022?", options: ["Inglaterra", "Países Bajos", "Francia", "España"], correct: 0 },
        { q: "¿Quién es el DT que fue capitán en el Mundial 2002?", options: ["El Hadji Diouf", "Aliou Cissé", "Papa Bouba Diop", "Salif Diao"], correct: 1 },
        { q: "¿En qué continente se encuentra Senegal?", options: ["Asia", "Europa", "África", "Oceanía"], correct: 2 },
        { q: "¿Cuál es el color principal del primer uniforme de Senegal?", options: ["Blanco", "Verde", "Rojo", "Amarillo"], correct: 0 },
        { q: "¿A qué selección sudamericana derrotó Senegal en 2022?", options: ["Uruguay", "Colombia", "Ecuador", "Perú"], correct: 2 },
        { q: "¿Quién anotó el gol de la victoria contra Francia en 2002?", options: ["Papa Bouba Diop", "Sadio Mané", "Henri Camara", "El Hadji Diouf"], correct: 0 }
    ],
    "RSA": [
        { q: "¿En qué año organizó Sudáfrica el Mundial de Fútbol?", options: ["2006", "2010", "2014", "2002"], correct: 1 },
        { q: "¿Cuál es el apodo de la selección sudafricana?", options: ["Los Elefantes", "Bafana Bafana", "Los Springboks", "Leones Indomables"], correct: 1 },
        { q: "¿Quién anotó el primer gol del Mundial 2010 ante México?", options: ["Siphiwe Tshabalala", "Steven Pienaar", "Benni McCarthy", "Katlego Mphela"], correct: 0 },
        { q: "¿Cómo se llama el instrumento ruidoso famoso en 2010?", options: ["Maraca", "Vuvuzela", "Tambor", "Silbato"], correct: 1 },
        { q: "¿Cuál es el color principal de su uniforme?", options: ["Verde", "Amarillo", "Blanco", "Rojo"], correct: 1 },
        { q: "¡Qué líder político inspiró al equipo en el Mundial?", options: ["Nelson Mandela", "Desmond Tutu", "Thabo Mbeki", "Cyril Ramaphosa"], correct: 0 },
        { q: "¿Cuál es el máximo goleador histórico de Sudáfrica?", options: ["Benni McCarthy", "Quinton Fortune", "Lucas Radebe", "Shaun Bartlett"], correct: 0 },
        { q: "¿En qué confederación juega Sudáfrica?", options: ["UEFA", "CAF", "AFC", "CONCACAF"], correct: 1 },
        { q: "¿A qué potencia europea derrotó Sudáfrica en 2010?", options: ["Francia", "España", "Inglaterra", "Italia"], correct: 0 },
        { q: "¿Cuál es la capital administrativa de Sudáfrica?", options: ["Ciudad del Cabo", "Pretoria", "Johannesburgo", "Durban"], correct: 1 }
    ],
    "SUI": [
        { q: "¿Cuál es el apodo de la selección de Suiza?", options: ["La Armada Roja", "La Nati", "El Reloj Suizo", "Los Alpes"], correct: 1 },
        { q: "¿En qué año organizó Suiza el Mundial?", options: ["1954", "1938", "1962", "1974"], correct: 0 },
        { q: "¿A qué fase llegó Suiza como máximo en un Mundial?", options: ["Octavos", "Cuartos de final", "Semifinales", "Tercer lugar"], correct: 1 },
        { q: "¿Qué selección eliminó a Suiza en octavos de 2022?", options: ["España", "Brasil", "Portugal", "Francia"], correct: 2 },
        { q: "¿Quién es el portero suizo que destacó recientemente?", options: ["Yann Sommer", "Gregor Kobel", "Diego Benaglio", "Pascal Zuberbühler"], correct: 0 },
        { q: "¡Qué jugador de origen kosovar es líder del mediocampo?", options: ["Xherdan Shaqiri", "Granit Xhaka", "Manuel Akanji", "Breel Embolo"], correct: 1 },
        { q: "¿Cuál es el color principal del uniforme suizo?", options: ["Rojo", "Blanco", "Azul", "Verde"], correct: 0 },
        { q: "¿A qué selección eliminó Suiza en la Euro 2021?", options: ["Alemania", "Francia", "Italia", "España"], correct: 1 },
        { q: "¿En qué ciudad se encuentra la sede de la FIFA?", options: ["Ginebra", "Basilea", "Zúrich", "Berna"], correct: 2 },
        { q: "¡Qué delantero suizo le anotó a Camerún (su país natal)?", options: ["Breel Embolo", "Haris Seferović", "Mario Gavranović", "Noah Okafor"], correct: 0 }
    ],
    "TUN": [
        { q: "¿Cuál es el apodo de la selección de Túnez?", options: ["Águilas de Cartago", "Los Zorros", "Los Halcones", "Los Leones"], correct: 0 },
        { q: "¿En qué año logró Túnez la primera victoria africana en un Mundial?", options: ["1970", "1978", "1982", "1994"], correct: 1 },
        { q: "¿A qué selección campeona del mundo derrotó Túnez en 2022?", options: ["Dinamarca", "Australia", "Francia", "Brasil"], correct: 2 },
        { q: "¿Cuántas veces ha pasado Túnez a octavos en un Mundial?", options: ["1 vez", "2 veces", "Nunca", "3 veces"], correct: 2 },
        { q: "¿Cuál es el color principal de su uniforme?", options: ["Blanco", "Verde", "Azul", "Amarillo"], correct: 0 },
        { q: "¿En qué confederación compite Túnez?", options: ["AFC", "CAF (África)", "UEFA", "CONCACAF"], correct: 1 },
        { q: "¿Cuál es el idioma oficial de Túnez?", options: ["Inglés", "Árabe", "Español", "Alemán"], correct: 1 },
        { q: "¿Quién es su capitán y figura histórica reciente?", options: ["Wahbi Khazri", "Youssef Msakni", "Hannibal Mejbri", "Ellyes Skhiri"], correct: 0 },
        { q: "¿Contra qué país empató Túnez en su debut de Qatar 2022?", options: ["Francia", "Dinamarca", "Australia", "Marruecos"], correct: 1 },
        { q: "¿En qué continente está ubicado Túnez?", options: ["África", "Asia", "Europa", "Oceanía"], correct: 0 }
    ],
    "URU": [
        { q: "¿Quién ganó el primer Mundial de la historia en 1930?", options: ["Argentina", "Francia", "Brasil", "Uruguay"], correct: 3 },
        { q: "¿Cuántos Mundiales reconoce la FIFA que tiene Uruguay?", options: ["1", "3", "2", "4"], correct: 3 },
        { q: "¿Cómo se llama su estadio principal en Montevideo?", options: ["Centenario", "Campeón del Siglo", "Gran Parque Central", "El Cilindro"], correct: 0 },
        { q: "¿Quién fue elegido el mejor jugador del Mundial 2010?", options: ["Diego Forlán", "Luis Suárez", "Edinson Cavani", "Diego Lugano"], correct: 0 },
        { q: "¿Qué jugador fue sancionado por una mordida en 2014?", options: ["Diego Godín", "Luis Suárez", "Álvaro Pereira", "Muslera"], correct: 1 },
        { q: "¿Contra qué país jugaron la final de 1930?", options: ["Brasil", "Yugoslavia", "Argentina", "EE.UU."], correct: 2 },
        { q: "¿Cuál es el apodo más común de la selección?", options: ["La Albiceleste", "La Celeste", "Los Canarios", "La Garra"], correct: 1 },
        { q: "¿Quién anotó el gol decisivo en el Maracanazo?", options: ["Obdulio Varela", "Héctor Scarone", "Juan Schiaffino", "Alcides Ghiggia"], correct: 3 },
        { q: "¿Quién es el actual DT de Uruguay?", options: ["Óscar Tabárez", "Jorge Fossati", "Diego Alonso", "Marcelo Bielsa"], correct: 3 },
        { q: "¿A qué confederación pertenece Uruguay?", options: ["CONCACAF", "UEFA", "CONMEBOL", "AFC"], correct: 2 }
    ],
    "UZB": [
        { q: "¿Cuál es el apodo de la selección de Uzbekistán?", options: ["Los Lobos Blancos", "Los Tigres", "Los Halcones", "Los Guerreros del Este"], correct: 0 },
        { q: "¿En qué confederación compite Uzbekistán?", options: ["UEFA", "AFC (Asia)", "CAF", "CONCACAF"], correct: 1 },
        { q: "¿Cuál es el color principal de su uniforme?", options: ["Azul", "Blanco", "Rojo", "Verde"], correct: 1 },
        { q: "¿Cuál es la capital de Uzbekistán?", options: ["Taskent", "Samarcanda", "Bujará", "Jiva"], correct: 0 },
        { q: "¿Quién es su máximo goleador histórico?", options: ["Eldor Shomurodov", "Maxim Shatskikh", "Server Djeparov", "Odil Ahmedov"], correct: 0 },
        { q: "¿Qué jugador uzbeko destacó en la AS Roma?", options: ["Server Djeparov", "Eldor Shomurodov", "Odil Ahmedov", "Igor Sergeev"], correct: 1 },
        { q: "¿Ha clasificado Uzbekistán alguna vez a un Mundial de mayores?", options: ["Sí", "Nunca", "En 2006", "En 2018"], correct: 1 },
        { q: "¿En qué región de Asia se encuentra Uzbekistán?", options: ["Asia Oriental", "Sudeste Asiático", "Asia Central", "Medio Oriente"], correct: 2 },
        { q: "¿Cuál es el estadio principal de Taskent?", options: ["Estadio Bunyodkor", "Estadio Pakhtakor", "Estadio Nacional", "Estadio Olímpico"], correct: 1 },
        { q: "¿Quién fue elegido mejor jugador de Asia dos veces (uzbeko)?", options: ["Odil Ahmedov", "Server Djeparov", "Maxim Shatskikh", "Ignatiy Nesterov"], correct: 1 }
    ],
    "BOL": [
        { q: "¿En qué año participó Bolivia por última vez en un Mundial?", options: ["1930", "1950", "1994", "2002"], correct: 2 },
        { q: "¿Quién anotó el único gol de Bolivia en los Mundiales (vs España 1994)?", options: ["Marco Etcheverry", "Erwin Sánchez", "Joaquín Botero", "Marcelo Martins"], correct: 1 },
        { q: "¿Cómo se llama su estadio más emblemático en La Paz?", options: ["Tahuichi Aguilera", "Hernando Siles", "Félix Capriles", "Víctor Agustín Ugarte"], correct: 1 },
        { q: "¿A qué selección enfrentó Bolivia en el inaugural de EE.UU. 1994?", options: ["Alemania", "Brasil", "España", "Corea del Sur"], correct: 0 },
        { q: "¿Qué apodo recibe la selección de Bolivia?", options: ["Los Cóndores", "La Verde", "El Altiplano", "Los Altiplánicos"], correct: 1 },
        { q: "¿En cuántos Mundiales ha participado Bolivia en total?", options: ["1", "2", "3", "5"], correct: 2 },
        { q: "¿Quién es el máximo ídolo histórico y figura en 1994?", options: ["Milton Melgar", "Marco Etcheverry", "Carlos Borja", "Juan Manuel Peña"], correct: 1 },
        { q: "¿En qué ciudad se encuentra el Estadio Ramón Tahuichi Aguilera?", options: ["La Paz", "Cochabamba", "Santa Cruz de la Sierra", "Sucre"], correct: 2 },
        { q: "¿Contra qué país debutó Bolivia en su primer Mundial (1930)?", options: ["Yugoslavia", "Argentina", "Francia", "Uruguay"], correct: 0 },
        { q: "¿Cuál es el mejor resultado de Bolivia en una Copa América?", options: ["Campeón (1963)", "Subcampeón", "Tercer lugar", "Cuarto lugar"], correct: 0 }
    ],
    "HON": [
        { q: "¿En qué año fue la primera participación de Honduras en un Mundial?", options: ["1970", "1982", "1990", "2010"], correct: 1 },
        { q: "¿Cómo se llama el estadio más emblemático en San Pedro Sula?", options: ["Tiburcio Carías", "Olímpico Metropolitano", "Nilmo Edwards", "Francisco Morazán"], correct: 1 },
        { q: "¿Quién es el máximo goleador histórico de Honduras?", options: ["Carlos Pavón", "David Suazo", "Jerry Bengtson", "Carlo Costly"], correct: 0 },
        { q: "¿A qué selección europea le empató en su debut en España 1982?", options: ["Yugoslavia", "Irlanda del Norte", "España", "Italia"], correct: 2 },
        { q: "¿Qué apodo recibe la selección de Honduras?", options: ["Los Catrachos", "Los Bicolor", "La H", "Todas las anteriores"], correct: 3 },
        { q: "¿Quién anotó el gol de Honduras contra Ecuador en Brasil 2014?", options: ["Roger Espinoza", "Carlo Costly", "Boniek García", "Wilson Palacios"], correct: 1 },
        { q: "¿Cuántas veces consecutivas clasificó a Mundiales recientemente?", options: ["Ninguna", "Dos (2010 y 2014)", "Tres", "Una (2010)"], correct: 1 },
        { q: "¿En qué ciudad se encuentra el Estadio Nacional Chelato Uclés?", options: ["San Pedro Sula", "Tegucigalpa", "La Ceiba", "Choluteca"], correct: 1 },
        { q: "¿Quién era el entrenador de Honduras en España 82?", options: ["Reinaldo Rueda", "Luis Fernando Suárez", "Chelato Uclés", "Ramón Maradiaga"], correct: 2 },
        { q: "¿Cuál ha sido el máximo logro de Honduras en una Copa América?", options: ["Campeón", "Tercer Lugar (2001)", "Subcampeón", "Cuartos de final"], correct: 1 }
    ],
    "MLI": [
        { q: "¿Cuántas veces ha clasificado Malí a un Mundial absoluto?", options: ["1 vez", "2 veces", "Ninguna", "5 veces"], correct: 2 },
        { q: "¿Quién es el futbolista más legendario de Malí (brilló en Sevilla)?", options: ["Salif Keïta", "Frédéric Kanouté", "Seydou Keita", "Mahamadou Diarra"], correct: 1 },
        { q: "¿Cómo se llama el estadio nacional principal en Bamako?", options: ["Stade du 26 Mars", "Stade Modibo Kéïta", "Stade Mamadou Konaté", "Stade de Segou"], correct: 0 },
        { q: "¿En qué posición quedó Malí en el Mundial Sub-17 de 2015?", options: ["Campeón", "Subcampeón", "Tercer lugar", "Cuarto lugar"], correct: 1 },
        { q: "¿Qué apodo recibe la selección de fútbol de Malí?", options: ["Los Elefantes", "Las Águilas", "Los Leones", "Los Leopardos"], correct: 1 },
        { q: "¿Quién ganó más títulos (incluyendo Champions con Barça)?", options: ["Djila Diarra", "Seydou Keita", "Moussa Marega", "Adama Traoré"], correct: 1 },
        { q: "¿Cuál es el color principal del uniforme de Malí?", options: ["Rojo", "Verde", "Amarillo", "Blanco"], correct: 2 },
        { q: "¿Qué torneo continental casi gana Malí en 1972?", options: ["Copa Oro", "Copa Africana de Naciones", "Copa Asia", "Eurocopa"], correct: 1 },
        { q: "¿En qué ciudad de Malí se encuentra el Stade Modibo Kéïta?", options: ["Bamako", "Tombuctú", "Kayes", "Mopti"], correct: 0 },
        { q: "¿Qué estrella actual del Tottenham representa a Malí?", options: ["Yves Bissouma", "Amadou Haidara", "Hamari Traoré", "Diadie Samassékou"], correct: 0 }
    ],
    "OMA": [
        { q: "¿Ha participado Omán alguna vez en un Mundial de la FIFA?", options: ["Sí, en 2002", "Sí, en 2018", "No, nunca", "Sí, en 1994"], correct: 2 },
        { q: "¿Quién es el portero más famoso de Omán (Premier League)?", options: ["Ali Al-Habsi", "Faiz Al-Rushaidi", "Mazin Al-Kasbi", "Ahmed Al-Rawahi"], correct: 0 },
        { q: "¿Cómo se llama el estadio más importante de Omán?", options: ["Sultan Qaboos Sports Complex", "Al-Seeb Stadium", "Sur Sports Complex", "Salalah Stadium"], correct: 0 },
        { q: "¿En qué ciudad se encuentra el Complejo Sultán Qaboos?", options: ["Salalah", "Mascate", "Sohar", "Sur"], correct: 1 },
        { q: "¿Qué apodo recibe la selección de Omán?", options: ["Los Rojos", "Los Halcones", "Los Guerreros", "Los Guerreros de Mascate"], correct: 0 },
        { q: "¿En qué confederación de fútbol compite Omán?", options: ["Africana", "Asiática", "Europea", "Oceanía"], correct: 1 },
        { q: "¿Qué torneo regional ganó Omán en 2009 y 2017-18?", options: ["Copa de Asia", "Copa del Golfo", "Copa Árabe", "Campeonato SAFF"], correct: 1 },
        { q: "¿Cuál es el color de la primera equipación de Omán?", options: ["Blanco", "Rojo", "Azul", "Verde"], correct: 1 },
        { q: "¿Quién es el máximo goleador histórico de Omán?", options: ["Hani Al-Dhabit", "Imad Al-Hosni", "Fawzi Bashir", "Ahmed Mubarak"], correct: 3 },
        { q: "¿Qué entrenador francés dirigió a Omán?", options: ["Hervé Renard", "Claude Le Roy", "Bruno Metsu", "Philippe Troussier"], correct: 1 }
    ],
    "COD": [
        { q: "¿Bajo qué nombre participó en su único Mundial (1974)?", options: ["Congo Belga", "Zaire", "RDC", "Katanga"], correct: 1 },
        { q: "¿Qué apodo recibe la selección de la RDC?", options: ["Los Elefantes", "Los Leopardos", "Los Leones Indomables", "Las Águilas"], correct: 1 },
        { q: "¿Cuál es el estadio más grande del país en Kinsasa?", options: ["Stade des Martyrs", "Stade Tata Raphaël", "Stade Kibassa Maliba", "Stade de la Concorde"], correct: 0 },
        { q: "¿En qué país se celebró el Mundial de 1974 donde participó?", options: ["México", "Alemania Federal", "Argentina", "Inglaterra"], correct: 1 },
        { q: "¿Qué famoso portero de Zaire hacía un baile peculiar?", options: ["Robert Kidiaba", "Kazadi Mwamba", "Pascal Kalemba", "Ley Matampi"], correct: 1 },
        { q: "¿Contra qué selección sufrió la goleada de 9-0 en 1974?", options: ["Brasil", "Yugoslavia", "Escocia", "Holanda"], correct: 1 },
        { q: "¿Qué jugador pateó el balón antes que el rival en un tiro libre?", options: ["Mwepu Ilunga", "Mulamba N'Daye", "Kakoko Etepe", "Mayanga Maku"], correct: 0 },
        { q: "¿Cuántas veces ha ganado la RDC la Copa Africana?", options: ["Ninguna", "1 vez", "2 veces", "5 veces"], correct: 2 },
        { q: "¿En qué ciudad está el estadio del 'Rumble in the Jungle'?", options: ["Lubumbashi", "Goma", "Kinsasa", "Kisangani"], correct: 2 },
        { q: "¿Cuál es el club más exitoso, conocido por Kidiaba?", options: ["AS Vita Club", "TP Mazembe", "DC Motema Pembe", "Saint Eloi Lupopo"], correct: 1 }
    ],
    "ALB": [
        { q: "¿En qué año debutó Albania en la Eurocopa?", options: ["1990", "2000", "2016", "2024"], correct: 2 },
        { q: "¿Cómo se llama el moderno estadio nacional en Tirana?", options: ["Qemal Stafa", "Air Albania Stadium", "Loro Boriçi", "Elbasan Arena"], correct: 1 },
        { q: "¿Qué apodo recibe la selección de Albania?", options: ["Las Águilas", "Los Rojinegros", "Los Búnkeres", "El Gran Salto"], correct: 1 },
        { q: "¿Quién es el capitán histórico con más partidos?", options: ["Lorik Cana", "Elseid Hysaj", "Thomas Strakosha", "Armando Broja"], correct: 0 },
        { q: "¿Contra qué país logró su primera victoria en Eurocopa?", options: ["Suiza", "Francia", "Rumanía", "Italia"], correct: 2 },
        { q: "¿En qué ciudad se encuentra el Estadio Loro Boriçi?", options: ["Tirana", "Shkodër", "Durrës", "Vlorë"], correct: 1 },
        { q: "¿Cuál es el símbolo en su bandera y escudo?", options: ["Un león", "Águila de dos cabezas", "Una estrella", "Un castillo"], correct: 1 },
        { q: "¿Quién es el entrenador brasileño de la Euro 2024?", options: ["Sylvinho", "Scolari", "Tite", "Dunga"], correct: 0 },
        { q: "¿En qué confederación juega Albania?", options: ["UEFA", "AFC", "CONCACAF", "CAF"], correct: 0 },
        { q: "¿Ha clasificado Albania alguna vez a un Mundial?", options: ["Sí, en 1982", "No, nunca", "Sí, en 2014", "Sí, en 1930"], correct: 1 }
    ]
};